version: '3'
services:
  db:
    image: mariadb:10.2.12
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_PORT=3306
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  solr:
    build:
      context: ./solr
    ports:
    - "18983:8983"
    entrypoint:
    - docker-entrypoint.sh
    - solr-foreground
  web:
    build:
      context: ./api_server
      args:
        - MYSQL_DATABASE=docker
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=docker
        - MYSQL_HOST=db
        - SOLR_URL=http://solr:8983/solr/mycore
    ports:
      - "9000:8080"
    links:
      - db
      - solr
