# Generated by Django 2.0.1 on 2018-01-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('year', models.IntegerField()),
                ('bureau', models.CharField(max_length=56)),
                ('head', models.CharField(max_length=256)),
                ('head_number', models.IntegerField()),
                ('sub_head', models.CharField(max_length=256)),
                ('sub_head_number', models.IntegerField(null=True)),
                ('controlling_officer_title', models.CharField(max_length=256)),
                ('controlling_officer_name', models.CharField(max_length=256)),
                ('programme', models.CharField(max_length=256)),
                ('reply_serial_no', models.CharField(max_length=256)),
                ('member', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('member_question_no', models.IntegerField()),
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('keywords', models.ManyToManyField(to='budget.Keyword')),
            ],
        ),
    ]
