# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau', models.IntegerField()),
                ('name_ch', models.CharField(max_length=256)),
                ('name_en', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Bureau')),
            ],
        ),
    ]
