# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ch', models.TextField(max_length=4096)),
                ('text_en', models.TextField(max_length=4096)),
                ('title_ch', models.CharField(max_length=4096)),
                ('title_en', models.CharField(max_length=4096)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1024)),
                ('key', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
