# Generated by Django 2.0.1 on 2018-01-13 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=512)),
                ('name_ch', models.CharField(max_length=512)),
                ('image', models.CharField(blank=True, default=None, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=512)),
                ('name_ch', models.CharField(max_length=512)),
                ('image', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('keywords', models.CharField(blank=True, default=None, max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.Party'),
        ),
    ]
