# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=512)),
                ('name_ch', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSENT', 'Absent'), ('ABSTAIN', 'Abstain')], default='NO', max_length=64)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meeting_type', models.CharField(default=None, max_length=1024)),
                ('key', models.CharField(blank=True, default='no-key', max_length=255, null=True, unique=True)),
                ('source_url', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingHansard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meeting_type', models.CharField(default='cm', max_length=128)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('source_url', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPersonel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ch', models.CharField(max_length=100)),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ch', models.CharField(max_length=100)),
                ('text_ch', models.TextField(default='', max_length=33554432)),
                ('bookmark', models.CharField(max_length=100)),
                ('sequence_number', models.IntegerField(default=0)),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
                ('others_individual', models.ManyToManyField(related_name='others', to='legco.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=512)),
                ('name_ch', models.CharField(max_length=512)),
                ('mover_type', models.CharField(max_length=512)),
                ('mover_ch', models.CharField(default=None, max_length=512, null=True)),
                ('mover_en', models.CharField(default=None, max_length=512, null=True)),
                ('mover_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('vote_number', models.IntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Meeting')),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Motion')),
            ],
        ),
        migrations.CreateModel(
            name='VoteSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('FUNC', 'Functional'), ('OVER', 'Overall'), ('GEOG', 'GEOG')], max_length=64)),
                ('present_count', models.IntegerField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('abstain_count', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=512)),
                ('vote', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='legco.Vote')),
            ],
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='clerks',
            field=models.ManyToManyField(related_name='clerks', to='legco.MeetingPersonel'),
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='members_absent',
            field=models.ManyToManyField(related_name='absent', to='legco.MeetingPersonel'),
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='members_present',
            field=models.ManyToManyField(related_name='present', to='legco.MeetingPersonel'),
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='public_officers',
            field=models.ManyToManyField(related_name='officers', to='legco.MeetingPersonel'),
        ),
        migrations.AddField(
            model_name='meetinghansard',
            name='speeches',
            field=models.ManyToManyField(to='legco.MeetingSpeech'),
        ),
        migrations.AddField(
            model_name='individualvote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Vote'),
        ),
        migrations.AddField(
            model_name='importantmotion',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Motion'),
        ),
    ]
