# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0002_auto_20180213_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinghansard',
            name='speeches',
            field=models.ManyToManyField(related_name='speeches', to='legco.MeetingSpeech'),
        ),
    ]
