# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0003_auto_20180214_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinghansard',
            name='speeches',
            field=models.ManyToManyField(related_name='hansard', to='legco.MeetingSpeech'),
        ),
    ]
