# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0004_auto_20180214_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('link', models.CharField(default='', max_length=1024)),
                ('question', models.TextField(default='', max_length=33554432)),
                ('answer', models.TextField(default='', max_length=33554432)),
                ('responder', models.CharField(max_length=255)),
                ('question_type', models.CharField(max_length=512)),
                ('title_ch', models.CharField(default='', max_length=512)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legco.Individual')),
                ('keywords', models.ManyToManyField(to='legco.Keyword')),
            ],
        ),
    ]
