# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-25 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinghansard',
            name='keywords',
            field=models.ManyToManyField(to='legco.Keyword'),
        ),
    ]
