# Generated by Django 2.1.7 on 2019-03-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinghansard',
            name='keywords',
            field=models.ManyToManyField(to='legco.Keyword'),
        ),
        migrations.AlterField(
            model_name='importantmotion',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Motion'),
        ),
        migrations.AlterField(
            model_name='individualvote',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Individual'),
        ),
        migrations.AlterField(
            model_name='individualvote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Vote'),
        ),
        migrations.AlterField(
            model_name='meetingpersonel',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Individual'),
        ),
        migrations.AlterField(
            model_name='meetingspeech',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Individual'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='mover_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Individual'),
        ),
        migrations.AlterField(
            model_name='question',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Individual'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Meeting'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Motion'),
        ),
        migrations.AlterField(
            model_name='votesummary',
            name='vote',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Vote'),
        ),
    ]
