# Generated by Django 2.0 on 2019-09-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0006_auto_20190310_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=512)),
                ('name_ch', models.CharField(max_length=512)),
                ('start_year', models.IntegerField(default=0)),
                ('chairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chair', to='legco.Individual')),
                ('individuals', models.ManyToManyField(to='legco.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Council')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilMembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GC', 'Geographical Constituencies'), ('FC_DC', 'Functional Constituency District Council (Second)'), ('FC', 'Functional Constituency')], max_length=128)),
                ('sub_category', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='councilmember',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legco.CouncilMembershipType'),
        ),
        migrations.AddField(
            model_name='council',
            name='members',
            field=models.ManyToManyField(related_name='member', through='legco.CouncilMember', to='legco.Individual'),
        ),
    ]
