# Generated by Django 2.1.7 on 2019-11-05 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0008_auto_20191024_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 5, 15, 16, 43, 363900), editable=False)),
                ('message', models.CharField(max_length=512)),
                ('model_class_name', models.CharField(max_length=512)),
                ('model_key', models.PositiveIntegerField()),
            ],
        ),
    ]
