# Generated by Django 2.1.7 on 2019-11-05 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0009_eventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 15, 18, 19, 644547), editable=False),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='model_key',
            field=models.CharField(max_length=512),
        ),
    ]
