# Generated by Django 2.1.7 on 2019-11-10 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legco', '0010_auto_20191105_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 12, 31, 34, 901239), editable=False),
        ),
        migrations.AlterField(
            model_name='motion',
            name='name_ch',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='motion',
            name='name_en',
            field=models.CharField(max_length=2048),
        ),
    ]
